version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${SECRET_KEY}
      DJANGO_DEBUG: ${DEBUG}
      DJANGO_SECURE_SSL_REDIRECT: ${SECURE_SSL_REDIRECT}
      DJANGO_SECURE_HSTS_SECONDS: ${SECURE_HSTS_SECONDS}
      DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: ${SECURE_HSTS_INCLUDE_SUBDOMAINS}
      DJANGO_SECURE_HSTS_PRELOAD: ${SECURE_HSTS_PRELOAD}
      DJANGO_SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      DJANGO_CSRF_COOKIE_SECURE: ${CSRF_COOKIE_SECURE}

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb

    ports:
      - "5432:5432"

volumes:
  postgres_data: